### ISSUE TITLE
Missing out on "åäö" in swedish keyboardlayot under linux mint 21.3 cinnamon wayland

### ISSUE THREAD

**Issue by ghost** [linuxmint/wayland#80]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA Geforce GTX 1650ti Mobile

### Frequency

Always

### Bug description

I cant get "åöä" swedish keyboardlayout to work under wayland in linux mint cinnamon

### Steps to reproduce

Choose wayland at login to system

### Expected behavior

That "åäö" should work

**Comment by mok0** [comment]
I have the same problem with a Danish keyboard. I seems it's set to US and I can't find a way to change it.

**Comment by steffenlongva** [comment]
Also same for Norwegian keyboard, æøå!

**Comment by mahtiankka** [comment]
The Finnish keyboard äää and ööö does not work on the Wayland side. Linux Mint 22 Wilma.

![Skandinavia_keys](https://github.com/linuxmint/wayland/assets/48694735/c0dc0221-52d4-4090-b332-8718472ee674)

**Comment by hecs** [comment]
Just adding some relevant info.
In Cinnamon, the layout-tab in Keyboard settings is hidden in Wayland.

It was made hidden here:
https://github.com/linuxmint/cinnamon/commit/5a73d4065f3ad757053dd5db931bc1372ade724e#diff-1835f7d0a380f612b62d5d63797ebff4ec9e60f77bf15ff63187c3c2278e35dd

Link to line:
https://github.com/linuxmint/cinnamon/blob/e0f64fbd78d69a26eafdf887dd1573c0af794829/files/usr/share/cinnamon/cinnamon-settings/modules/cs_keyboard.py#L621C40-L621C52

Is there a workaround so that one can set a specific keyboard layout in Wayland/Cinnamon?

**Comment by ericzolf** [comment]
There is a more generic issue #14 for this.

**Comment by JosephMcc** [comment]
As pointed out, this is a duplicate.
