### ISSUE TITLE
Wayland mode: ctrl+tap not working in browser

### ISSUE THREAD

**Issue by netikras** [linuxmint/wayland#85]
### Distribution

Mint 23.1

### Package version

6.0.4

### Graphics hardware in use

Intel (i7-13700H)

### Frequency

Always

### Bug description

So I downloaded and installed Mint just yesterday. If I log into the Cinnamon DE with Wayland, I can no longer ctrl+tap on links in chrome to have them open in new tab. The links simply open in the current tab. My guess is that ctrl+tap acts exactly as tap. If I switch back to x11, ctrl+tap works as expected -- in Chrome it opens the tapped link in a new tab.

I'm saying 'tap' because I only have a laptop with a touchpad.

I did switch to Wayland hoping to have touchpad gestures' support. But that didn't happen... If I enable gestures in the control panel, they do not seem to be working. At all. And even the three-finger-tap I configured as part of the touchpad configuration stopped working in Wayland.

### Steps to reproduce

1. Log into Cinnamon through Wayland
2. install google-chrome
3. control-click any link

### Expected behavior

the link should open in a new tab. Instead, it opens in the same tab

### Additional information

Yes, I've just tested -- some gestures work with x11 (is it x11 though? I mean the default graphics engine. I can't spot an x11 process with `ps -ef`.), but not all of them. I was hoping Wayland would offer better support for gestures. At least pinch gesture works in x11 (I'll keep on calling it x11 until I'm corrected) but even it doesn't work in Wayland

**Comment by HalcyonDays2010s** [comment]
I have another bug here that might be related:

When in a browser, normally you can zoom in/out using ctrl+mousewheel. However, on Mint 21.3 Cinnamon it appears the ctrl is ignored and ctrl+mousewheel behaves as is ctrl is not pressed (so it just scrolls instead of zooms).  Chrome, Brave, Firefox all the same.

I have added the bug to this report, because from the description it appears that the problem there too is that crtl is ignored when logged in as Wayland. In X11 all works fine

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/wayland/issues/1
