### ISSUE TITLE
polkit error on wayland

### ISSUE THREAD

**Issue by wang1zhen** [linuxmint/wayland#91]
### Distribution

LMDE 6

### Package version

6.0.4

### Frequency

Always

### Bug description

I installed LMDE yesterday and wished to do some tweaks. I preferred wayland so I login via a wayland session, but when dealing with some operations that requrie root access, the wayland session is not responding correctly. The prompt for password did not show up, and the error message is:

You are not allowed to perform this action

You don't have the required privileges to perform this action.

Details:

Code:

org.freedesktop.PolicyKit.Error.Failed: ('system-bus-name', {'name': ':1.196'}): org.debian.apt.install-or-remove-packages

I encountered this while trying to install some input methods from system settings.

And I can confirm that this problem does not show up in X11 session.

### Steps to reproduce

1. log in via cinnamon wayland
2. System Settings - Input Method, Select arbitrary language (for example, Japanese)
3. hit `install`
4. hit `continue`
5. There you go

### Expected behavior

Pop up a prompt for password

**Comment by haggen88** [comment]
#22  related

**Comment by JosephMcc** [comment]
Closing as a duplicate. This should be fixed in the next Cinnamon version.

**Comment by wang1zhen** [comment]
> Closing as a duplicate. This should be fixed in the next Cinnamon version.

Thanks, may I ask the release cycle of Cinnamon and will it be pushed to LMDE or Linux Mint soon?

**Comment by rcalixte** [comment]
> Thanks, may I ask the release cycle of Cinnamon and will it be pushed to LMDE or Linux Mint soon?

The typical adage is that each distro release will see a new version of Cinnamon as long as it is the latest. Since Mint 22.0 will be the next release, that will get the new version of Cinnamon while 21.x has seen its last Cinnamon release (but will still receive security updates). The same is true for LMDE. Since LMDE 6 is currently the most recent version, it will see a new version of Cinnamon until the release of LMDE 7 and the version of Cinnamon that is released with that. I hope this makes sense and helps.
